services:
  - type: web
    name: splitred-backend
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        value: sqlite:///./splitred.db
      - key: FLASK_ENV
        value: production
    plan: free
